-d C:\Users\Uncle\Desktop\FPGA\mini_star(1)\exp8_frequency_test\impl\gwsynthesis\FRE.vg
-p GW1NSR-4C-QFN48P-7
-pn GW1NSR-LV4CQN48PC7/I6
-cst C:\Users\Uncle\Desktop\FPGA\mini_star(1)\exp8_frequency_test\src\top_freq.cst
-cfg C:\Users\Uncle\Desktop\FPGA\mini_star(1)\exp8_frequency_test\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
