-d I:\Gowin\mini_star\exp3_key_led\impl\gwsynthesis\key_led.vg
-p GW1NSR-4C-QFN48P-7
-pn GW1NSR-LV4CQN48PC7/I6
-cst I:\Gowin\mini_star\exp3_key_led\src\key_led_top.cst
-cfg I:\Gowin\mini_star\exp3_key_led\impl\pnr\device.cfg
-sdc I:\Gowin\mini_star\exp3_key_led\src\key_led.sdc
-bit
-tr
-ph
-timing
